### ISSUE TITLE
Some images cropped when adding to covid-chestray-dataset

### ISSUE THREAD

**Issue by bganglia** [ml-workgroup/covid-19-image-repository#5]
Hi! While adding these images to @ieee8023's covid-chestxray-dataset, I cropped a few to cut out part of the black margin. I just wanted to share the filenames in case you were interested in doing the same thing.
```
00d96e05.png
17ad0a56.png
436a6348.png
4c0fcf57.png
4fed5061.png
6f7008af.png
76093afc.png
81089cb4.png
865336ed.png
a3111116.png
a4318ac9.png
b10c49ca.png
bace1e45.png
bb4c4038.png
cb706009.png
```
Thank you so much for making this resource available!

**Comment by liob** [comment]
@bganglia 
we are (finally) providing the un-altered images as nifti files. You may extract higher quality image data from this resource.
