### ISSUE TITLE
Lymphocyte_offset & neutrophil_offset meaning?

### ISSUE THREAD

**Issue by Cricetulus** [ml-workgroup/covid-19-image-repository#7]
Could you provide more explanation about these two variables?

**Comment by liob** [comment]
lymphocytes_offset and neutrophils_offset encodes the relative date offset in days. Positive values are in the future, negative values in the past, relative to the date when the image was created.

Currently, there is an internal issue with the date offset calculation. Please see #6 for tracking this issue.

**Comment by liob** [comment]
Issue #6 has been resolved with Version 2.0.
