### ISSUE TITLE
Radiological findings

### ISSUE THREAD

**Issue by armiro** [ml-workgroup/covid-19-image-repository#8]
While I appreciate your great work providing images in a public repo, not having labels for images is a problem in my point of view. I have read your guideline for assuming COVID-positive/negative based on admission-offset but some of the CXRs are not clearly having radiological findings of pneumonia. 

For example, CXR with `patient_id=d3fb252e` and `image_id=88859dc1` has an admission offset of 0 with most of the other metrics not reported; while it is assumed COVID-19 positive, I think CXR does not show specific findings related to pneumonia. If a radiologist's interpretation could be provided for the images it would be great.

**Comment by liob** [comment]
@armiro 
sorry for the late response. Not all patients with COVID develop typical radiological findings. Unfortunately, we will not be able to provide the radiological findings in text form. The risk of leaking patient identifying information is too high (also the text would be in german ...). The best advice I can give you is to exclude records that do not fulfill a set of specific constraints (which you need to define for your application).
