### ISSUE TITLE
CR vs DX

### ISSUE THREAD

**Issue by ieee8023** [ml-workgroup/covid-19-image-repository#9]
For modality what is the difference here?

**Comment by liob** [comment]
CR stands for Computed Radiography. This means, that the image is taken using an image plate with a digital picture developing process.

DX stands for Digital Radiography. This means, that the image is taken using a fully digitized process using a photon detector.

In practice, the CR images are taken at the bedside and have a generally worse image quality than the DX images, which are made in special rooms at the institute. You can put an image plate (CR) below a patient who is lying in a bed (potentially intubated). For the DX images the patient has to be able to at least sit up by himself.
